services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm start
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    # depends_on:
    #   - db
    ports:
      - '4000:4000'
      - '9229:9229'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=oseadb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
    
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./docker-volumes/redis:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - '8889:8081'
    environment:
      - REDIS_HOST=local:redis:6379
