services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm start
    volumes:
      - ./:/usr/src/app
    # depends_on:
    #   - db
    ports:
      - '4000:4000'
      - '9229:9229'
    
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./docker-volumes/redis:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - '8889:8081'
    environment:
      - REDIS_HOST=local:redis:6379